/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ExperienceTrainingRouteImport } from './routes/experience.training'
import { Route as ExperienceIpsasRouteImport } from './routes/experience.ipsas'
import { Route as ExperienceIfrsForSmesRouteImport } from './routes/experience.ifrs-for-smes'
import { Route as ExperienceConsultancyServicesRouteImport } from './routes/experience.consultancy-services'
import { Route as ExperienceAssetValuationRouteImport } from './routes/experience.asset-valuation'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceTrainingRoute = ExperienceTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceIpsasRoute = ExperienceIpsasRouteImport.update({
  id: '/ipsas',
  path: '/ipsas',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceIfrsForSmesRoute = ExperienceIfrsForSmesRouteImport.update({
  id: '/ifrs-for-smes',
  path: '/ifrs-for-smes',
  getParentRoute: () => ExperienceRoute,
} as any)
const ExperienceConsultancyServicesRoute =
  ExperienceConsultancyServicesRouteImport.update({
    id: '/consultancy-services',
    path: '/consultancy-services',
    getParentRoute: () => ExperienceRoute,
  } as any)
const ExperienceAssetValuationRoute =
  ExperienceAssetValuationRouteImport.update({
    id: '/asset-valuation',
    path: '/asset-valuation',
    getParentRoute: () => ExperienceRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/experience/asset-valuation': typeof ExperienceAssetValuationRoute
  '/experience/consultancy-services': typeof ExperienceConsultancyServicesRoute
  '/experience/ifrs-for-smes': typeof ExperienceIfrsForSmesRoute
  '/experience/ipsas': typeof ExperienceIpsasRoute
  '/experience/training': typeof ExperienceTrainingRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/experience/asset-valuation': typeof ExperienceAssetValuationRoute
  '/experience/consultancy-services': typeof ExperienceConsultancyServicesRoute
  '/experience/ifrs-for-smes': typeof ExperienceIfrsForSmesRoute
  '/experience/ipsas': typeof ExperienceIpsasRoute
  '/experience/training': typeof ExperienceTrainingRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/experience/asset-valuation': typeof ExperienceAssetValuationRoute
  '/experience/consultancy-services': typeof ExperienceConsultancyServicesRoute
  '/experience/ifrs-for-smes': typeof ExperienceIfrsForSmesRoute
  '/experience/ipsas': typeof ExperienceIpsasRoute
  '/experience/training': typeof ExperienceTrainingRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/services'
    | '/admin/blog'
    | '/admin/messages'
    | '/blog/$slug'
    | '/experience/asset-valuation'
    | '/experience/consultancy-services'
    | '/experience/ifrs-for-smes'
    | '/experience/ipsas'
    | '/experience/training'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/services'
    | '/admin/blog'
    | '/admin/messages'
    | '/blog/$slug'
    | '/experience/asset-valuation'
    | '/experience/consultancy-services'
    | '/experience/ifrs-for-smes'
    | '/experience/ipsas'
    | '/experience/training'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/services'
    | '/admin/blog'
    | '/admin/messages'
    | '/blog/$slug'
    | '/experience/asset-valuation'
    | '/experience/consultancy-services'
    | '/experience/ifrs-for-smes'
    | '/experience/ipsas'
    | '/experience/training'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/training': {
      id: '/experience/training'
      path: '/training'
      fullPath: '/experience/training'
      preLoaderRoute: typeof ExperienceTrainingRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/ipsas': {
      id: '/experience/ipsas'
      path: '/ipsas'
      fullPath: '/experience/ipsas'
      preLoaderRoute: typeof ExperienceIpsasRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/ifrs-for-smes': {
      id: '/experience/ifrs-for-smes'
      path: '/ifrs-for-smes'
      fullPath: '/experience/ifrs-for-smes'
      preLoaderRoute: typeof ExperienceIfrsForSmesRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/consultancy-services': {
      id: '/experience/consultancy-services'
      path: '/consultancy-services'
      fullPath: '/experience/consultancy-services'
      preLoaderRoute: typeof ExperienceConsultancyServicesRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/experience/asset-valuation': {
      id: '/experience/asset-valuation'
      path: '/asset-valuation'
      fullPath: '/experience/asset-valuation'
      preLoaderRoute: typeof ExperienceAssetValuationRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExperienceRouteChildren {
  ExperienceAssetValuationRoute: typeof ExperienceAssetValuationRoute
  ExperienceConsultancyServicesRoute: typeof ExperienceConsultancyServicesRoute
  ExperienceIfrsForSmesRoute: typeof ExperienceIfrsForSmesRoute
  ExperienceIpsasRoute: typeof ExperienceIpsasRoute
  ExperienceTrainingRoute: typeof ExperienceTrainingRoute
}

const ExperienceRouteChildren: ExperienceRouteChildren = {
  ExperienceAssetValuationRoute: ExperienceAssetValuationRoute,
  ExperienceConsultancyServicesRoute: ExperienceConsultancyServicesRoute,
  ExperienceIfrsForSmesRoute: ExperienceIfrsForSmesRoute,
  ExperienceIpsasRoute: ExperienceIpsasRoute,
  ExperienceTrainingRoute: ExperienceTrainingRoute,
}

const ExperienceRouteWithChildren = ExperienceRoute._addFileChildren(
  ExperienceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
